
# Post \#61235853 [Link](https://stackoverflow.com/questions/61235853/)

## How to invoke Cloud Function from Cloud Scheduler with Authentication

**Vote**: 16 (306/702) **Views**: 9887 (417/702) 

**Internal ID** \#1-3-246

Created at 2020-04-15 18:19:31

Tags: `python` `authentication` `google-cloud-functions` `google-cloud-scheduler`

----------

#### Metadata:

Area: `Data Science & Machine Learning`

Language: `python` (full parsed tag list: `python`)

----------

**Notepad**


----------

I've looked everywhere and it seems people either use pubsub, app engine http or http with no auth. Not too many people out there showing their work for accessing functions via authentication w/ oidc tokens to access google functions. 

I checked out: [Cannot invoke Google Cloud Function from GCP Scheduler](https://stackoverflow.com/questions/60055422/cannot-invoke-google-cloud-function-from-gcp-scheduler) but nothing seemed to work.

Documentation I followed:
[https://cloud.google.com/scheduler/docs/http-target-auth#using-gcloud_1](https://cloud.google.com/scheduler/docs/http-target-auth#using-gcloud_1)


1. created a new service account
2. set roles (Cloud scheduler service agent/Cloud functions service agent/Cloud scheduler admin/cloud functions invoker...even tried owner!)
3. deployed google function that doesn't allow public (unauthenticated) access (a simple helloworld function)
4. setup cron job on cloud scheduler to run every minute against the new deployed function with this configuration: url = helloworld function oidc-token newly created service account audience set to hello world function url



outcome on cloud scheduler logs:

```
Expand all | Collapse all{
 httpRequest: {
 }
 insertId: "ibboa4fg7l1s9"  
 jsonPayload: {
  @type: "type.googleapis.com/google.cloud.scheduler.logging.AttemptFinished"   
  jobName: "projects/project/locations/region/jobs/tester"   
  status: "PERMISSION_DENIED"   
  targetType: "HTTP"   
  url: "https://region-project.cloudfunctions.net/tester"   
 }
 logName: "projects/project/logs/cloudscheduler.googleapis.com%2Fexecutions"  
 receiveTimestamp: "2020-04-15T17:50:14.287689800Z"  
 resource: {â€¦}  
 severity: "ERROR"  
 timestamp: "2020-04-15T17:50:14.287689800Z"
```


I saw one solution that showed someone creating a new project to get to this to work, are there any others??

Appreciate any help provided.



[New Google Function - running in central (same as my app engine app)](https://i.stack.imgur.com/8ZRRI.png)

[New Service Account - w/ Owner role](https://i.stack.imgur.com/30vXE.png)

[New Scheduled Task - Info](https://i.stack.imgur.com/1Qtr3.png)

[New Scheduled Task - Status](https://i.stack.imgur.com/60cRd.png)

[New Scheduled Task - Logs](https://i.stack.imgur.com/2tXjp.png)



If you're missing the cloudscheduler service account (ex:
service-1231231231412@gcp-sa-cloudscheduler.iam.gserviceaccount.com)
Http auth tasks wont work.
To fix, I had to disable api and renable and it gave me the service account,
I didnt use this service account but, that was the only changing factor after I did this to make it work.


----------
        
## GPT4 Attempt \#0

It seems like you've done most of the steps correctly, but the PERMISSION_DENIED error suggests that the service account you're using doesn't have the right permissions to invoke the Cloud Function.

Here are a few things you could try:

1. **Check the service account permissions again**: Make sure that the service account you're using has the `roles/cloudfunctions.invoker` role. This role allows the service account to invoke the Cloud Function.

2. **Check the audience field**: The audience field in the Cloud Scheduler job should be set to the URL of the Cloud Function you're trying to invoke.

3. **Check the service account email**: Make sure you're using the correct service account email in the Cloud Scheduler job.

4. **Check the Cloud Function permissions**: Go to the Cloud Function details page in the Google Cloud Console, click on the "Permissions" tab, and make sure that the service account is listed there with the `roles/cloudfunctions.invoker` role.

5. **Re-deploy the Cloud Function**: Sometimes, changes to the service account permissions might not take effect immediately. Try re-deploying the Cloud Function and see if that helps.

6. **Check the Cloud Scheduler logs**: The logs might provide more details about why the invocation is failing. You can view the logs in the Google Cloud Console.

If none of these steps work, you might want to consider creating a new project and trying the same steps there. Sometimes, there might be project-level settings or permissions that are causing the issue.

--------

## GPT4 Attempt \#1

It seems like you've done most of the steps correctly. However, the error message `PERMISSION_DENIED` indicates that the service account you're using doesn't have the necessary permissions to invoke the Cloud Function.

Here are some steps you can try:

1. **Ensure the service account has the correct permissions**: You mentioned that you've given the service account roles like Cloud Scheduler Service Agent, Cloud Functions Service Agent, Cloud Scheduler Admin, Cloud Functions Invoker, and even Owner. However, you need to ensure that the service account has the `roles/cloudfunctions.invoker` role for the specific Cloud Function you're trying to invoke. You can do this by going to the Cloud Function's permissions tab in the Google Cloud Console and adding the service account there with the `roles/cloudfunctions.invoker` role.

2. **Ensure the audience field is correct**: The audience field should be the URL of the function you're trying to invoke. Make sure there are no typos or incorrect characters in this field.

3. **Ensure the service account is being used correctly**: When you create the Cloud Scheduler job, you need to specify the service account to be used for the job. Make sure you're specifying the correct service account and that there are no typos or incorrect characters in the service account name.

4. **Check for any restrictions on the Cloud Function**: If the Cloud Function has any restrictions like VPC Service Controls or IAM Conditions, these could be preventing the Cloud Scheduler job from invoking the function. You would need to adjust these restrictions accordingly.

5. **Re-enable the Cloud Scheduler API**: As you mentioned, another user found success by disabling and then re-enabling the Cloud Scheduler API. This seems to have resolved an issue with the Cloud Scheduler service account not being created correctly. You could try this as well.

If none of these steps work, you might want to consider reaching out to Google Cloud Support for further assistance.

--------

## GPT4 Attempt \#2

It seems like you've done most of the steps correctly. Here are a few things you could check or try:

1. **IAM Permissions:** Make sure the service account you created has the `roles/cloudfunctions.invoker` role at the project level. This will allow the service account to invoke any Cloud Function in the project. You can do this by going to the IAM page in the Google Cloud Console, finding the service account, and adding the role.

2. **Audience Field:** The audience field should be set to the URL of the function you are trying to invoke. This is the same URL you put in the `URL` field of the Cloud Scheduler job.

3. **OIDC token:** Make sure you have selected `Add OIDC token` in the `Auth header` field of the Cloud Scheduler job. The `Service account` field should be the email of the service account you created.

4. **Function Permissions:** Make sure the function you are trying to invoke has the correct permissions. You can do this by going to the Cloud Functions page in the Google Cloud Console, clicking on the function, and then clicking on the `PERMISSIONS` tab. There should be a role for `allUsers` with the `Cloud Functions Invoker` role. If it's not there, you can add it by clicking `ADD MEMBER`, entering `allUsers` in the `New members` field, selecting `Cloud Functions Invoker` from the `Role` dropdown, and clicking `SAVE`.

5. **Re-enable Cloud Scheduler API:** If none of the above works, you could try disabling and then re-enabling the Cloud Scheduler API. This will create a new service account for the Cloud Scheduler, which might fix the issue.

If you're still having issues after trying these steps, it might be a good idea to reach out to Google Cloud Support for further assistance.

--------
