
# Post \#45724006 [Link](https://stackoverflow.com/questions/45724006/)

## Django - Reverse for '' not found. '' is not a valid view function or pattern name

**Vote**: 81 (77/702) **Views**: 262721 (26/702) 

**Internal ID** \#1-3-238

Created at 2017-08-16 22:36:26

Tags: `python` `django` `paypal` `render`

----------

#### Metadata:

Area: `Data Science & Machine Learning`

Language: `python` (full parsed tag list: `python`)

----------

**Notepad**


----------

I'm working on my project for a course and I'm totally stuck right now. I'm creating a website to sell products through paypal and the paypal return/cancel pages are not rendering properly. I've followed the examples in my lessons and checked the code a hundred times but obviously there is something I'm missing.

I'm getting an error when I go to products, click buy now, login to paypal and then either cancel the purchase or buy the product and return to merchant's page.
paypal_return.html and paypal_cancel.html are 2 templates saved under templates/paypal/ 

Can anybody see what I'm missing? 

Here you can see the full code [https://github.com/IreneG5/spss_online](https://github.com/IreneG5/spss_online)

Traceback

```
Environment:


Request Method: GET
Request URL: http://127.0.0.1:8000/paypal-cancel/

Django Version: 1.11.4
Python Version: 2.7.12
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django_forms_bootstrap',
 'paypal.standard.ipn',
 'home',
 'accounts',
 'paypal_store',
 'products']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']


Template error:
In template C:\Users\irene\Documents\Full-Stack-Developer\Stream3\Project\spss_online\templates\base.html, error at line 10
   Reverse for '' not found. '' is not a valid view function or pattern name.   1 : {% load staticfiles %}
   2 : <!DOCTYPE html>
   3 : <html lang="en">
   4 : <head>
   5 :     <meta charset="UTF-8">
   6 :     <title>Buy SPSS Online</title>
   7 :     <meta name="viewport" content="width=device-width, initial-scale=1.0">
   8 :     <meta name="description" content="">
   9 :     <meta name="author" content="">
   10 :     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.3.7/cerulean/bootstrap.min.css">
   11 :     <link rel="stylesheet" href="{% static 'css/style.css' %}">
   12 : 
   13 : 
   14 : </head>
   15 : <body>
   16 : <div class="container">
   17 :     <div class='container-fluid'>
   18 :         <nav id="menu" class="navbar navbar-inverse">
   19 :             <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
   20 :                 <span class="icon-bar"></span>


Traceback:

File "C:\Users\irene\virtualenv\spss_online_env\lib\site-packages\django\core\handlers\exception.py" in inner
  41.             response = get_response(request)

File "C:\Users\irene\virtualenv\spss_online_env\lib\site-packages\django\core\handlers\base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "C:\Users\irene\virtualenv\spss_online_env\lib\site-packages\django\core\handlers\base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "C:\Users\irene\Documents\Full-Stack-Developer\Stream3\Project\spss_online\paypal_store\views.py" in paypal_cancel
  15.     return render(request, 'paypal/paypal_cancel.html', args)

File "C:\Users\irene\virtualenv\spss_online_env\lib\site-packages\django\shortcuts.py" in render
  30.     content = loader.render_to_string(template_name, context, request, using=using)

File "C:\Users\irene\virtualenv\spss_online_env\lib\site-packages\django\template\loader.py" in render_to_string
  68.     return template.render(context, request)

File "C:\Users\irene\virtualenv\spss_online_env\lib\site-packages\django\template\backends\django.py" in render
  66.             return self.template.render(context)

File "C:\Users\irene\virtualenv\spss_online_env\lib\site-packages\django\template\base.py" in render
  207.                     return self._render(context)

File "C:\Users\irene\virtualenv\spss_online_env\lib\site-packages\django\template\base.py" in _render
  199.         return self.nodelist.render(context)

File "C:\Users\irene\virtualenv\spss_online_env\lib\site-packages\django\template\base.py" in render
  990.                 bit = node.render_annotated(context)

File "C:\Users\irene\virtualenv\spss_online_env\lib\site-packages\django\template\base.py" in render_annotated
  957.             return self.render(context)

File "C:\Users\irene\virtualenv\spss_online_env\lib\site-packages\django\template\loader_tags.py" in render
  177.             return compiled_parent._render(context)

File "C:\Users\irene\virtualenv\spss_online_env\lib\site-packages\django\template\base.py" in _render
  199.         return self.nodelist.render(context)

File "C:\Users\irene\virtualenv\spss_online_env\lib\site-packages\django\template\base.py" in render
  990.                 bit = node.render_annotated(context)

File "C:\Users\irene\virtualenv\spss_online_env\lib\site-packages\django\template\base.py" in render_annotated
  957.             return self.render(context)

File "C:\Users\irene\virtualenv\spss_online_env\lib\site-packages\django\template\loader_tags.py" in render
  72.                 result = block.nodelist.render(context)

File "C:\Users\irene\virtualenv\spss_online_env\lib\site-packages\django\template\base.py" in render
  990.                 bit = node.render_annotated(context)

File "C:\Users\irene\virtualenv\spss_online_env\lib\site-packages\django\template\base.py" in render_annotated
  957.             return self.render(context)

File "C:\Users\irene\virtualenv\spss_online_env\lib\site-packages\django\template\defaulttags.py" in render
  458.             url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)

File "C:\Users\irene\virtualenv\spss_online_env\lib\site-packages\django\urls\base.py" in reverse
  91.     return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))

File "C:\Users\irene\virtualenv\spss_online_env\lib\site-packages\django\urls\resolvers.py" in _reverse_with_prefix
  497.         raise NoReverseMatch(msg)

Exception Type: NoReverseMatch at /paypal-cancel/
Exception Value: Reverse for '' not found. '' is not a valid view function or pattern name.
```



----------
        
## GPT4 Attempt \#0

The error message "Reverse for '' not found. '' is not a valid view function or pattern name." suggests that there is an issue with the URL routing in your Django application. Specifically, it seems like Django is trying to reverse a URL with an empty string as the view name, which is not valid.

Here are a few things you can check:

1. **Check your URL configuration**: Make sure that all your URLs are correctly defined in your `urls.py` file(s). Each URL should be associated with a valid view function or class-based view.

2. **Check your template files**: The error might be coming from a template where you are trying to reverse a URL using the `{% url %}` template tag. Make sure that you are providing a valid view name as an argument to this tag.

3. **Check your views**: If you are using the `reverse()` or `reverse_lazy()` function in your views or model methods to generate URLs, make sure that you are providing a valid view name as an argument.

Without access to your code, it's hard to provide a more specific solution. However, the error message suggests that the problem is likely related to the URL configuration or the way you are generating URLs in your templates or views. 

If you're still having trouble, please provide more details about your URL configuration and the places in your code where you are generating URLs.

--------

## GPT4 Attempt \#1

The error message is indicating that Django is unable to reverse a URL because it can't find a matching view function or pattern name. This is likely happening because in your template, you are using the `{% url %}` template tag with an empty string or a variable that is evaluating to an empty string.

The error is occurring at line 10 of your `base.html` file, but the code snippet you've provided doesn't seem to have a `{% url %}` tag at that line. It's possible that the error is in a different part of your template that extends or includes `base.html`.

Here are a few things you can check:

1. Look for any `{% url %}` tags in your templates. Make sure that the view name you're providing to the tag matches a name in your `urls.py` file.

2. If you're using a variable with the `{% url %}` tag, like `{% url my_view_name %}`, make sure that `my_view_name` is being correctly passed into the context of your template and that it's not an empty string.

3. Check your `urls.py` file to make sure all your URL patterns have a `name` attribute. The `name` attribute is what you should be using with the `{% url %}` tag.

4. If you're using namespaces with your URLs, you'll need to include the namespace in the `{% url %}` tag, like `{% url 'myapp:my_view_name' %}`.

Without seeing the actual template code, it's hard to give a more specific solution. But the error message is definitely indicating that the problem is with a `{% url %}` tag in one of your templates.

--------

## GPT4 Attempt \#2

The error message `Reverse for '' not found. '' is not a valid view function or pattern name.` suggests that there is an issue with the use of Django's `reverse` function in your templates or views. The `reverse` function is used to generate URLs by using the name of the view.

Here are a few things you can check:

1. **Check your URL configuration:** Make sure that all your views are correctly mapped to a URL pattern in your `urls.py` file and that each URL pattern has a unique name. The name you use in the `reverse` function should match exactly with the name in your URL configuration.

2. **Check your template files:** Look for any use of the `{% url %}` template tag. This tag also uses the `reverse` function under the hood. Make sure that the view name you are passing to the `{% url %}` tag matches with the name in your URL configuration.

3. **Check your views:** If you are using the `reverse` function in your views, make sure that the view name you are passing to the `reverse` function matches with the name in your URL configuration.

Without seeing the actual code, it's hard to pinpoint the exact issue. But the error message suggests that the `reverse` function is being called with an empty string as the view name, which is why it's not able to find a matching URL pattern. You need to find where this is happening and correct it.

--------
