
# Post \#63027020 [Link](https://stackoverflow.com/questions/63027020/)

## Problem with pip install mariadb - mariadb_config not found

**Vote**: 15 (318/702) **Views**: 25066 (262/702) 

**Internal ID** \#1-3-251

Created at 2020-07-22 04:42:48

Tags: `mysql` `python-3.x` `pip` `raspberry-pi` `mariadb`

----------

#### Metadata:

Area: `Data Science & Machine Learning`

Language: `python` (full parsed tag list: `python`)

----------

**Notepad**


----------

I have been trying to run `pip3 install mariadb` on my raspberry pi running ubuntu 18.04 and I was unsuccessful.
I have tried installing following packages as suggested in other answers:
```
sudo apt-get install mariadb-server
sudo apt-get install libmariadbclient-dev
sudo apt-get install libmysqlclient-dev

pip3 install mysqlclient
pip3 install mysql-connector-python-rf
```

However, I'm still running intto the problem as shown:
```
ubuntu@ubuntu:~$ pip3 install mariadb
Collecting mariadb
  Using cached https://files.pythonhosted.org/packages/8f/c9/7050899dc1066409a17e1147d3afe1b078e582afdb755c6d3cb9c9a5c3ab/mariadb-1.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    /bin/sh: 1: mariadb_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-2gdw_t_r/mariadb/setup.py", line 26, in <module>
        cfg = get_config(options)
      File "/tmp/pip-build-2gdw_t_r/mariadb/mariadb_posix.py", line 49, in get_config
        cc_version = mariadb_config(config_prg, "cc_version")
      File "/tmp/pip-build-2gdw_t_r/mariadb/mariadb_posix.py", line 27, in mariadb_config
        "mariadb_config not found.\nPlease make sure, that MariaDB Connector/C is installed on your system, edit the configuration file 'site.cfg' and set the 'mariadb_config'\noption, which should point to the mariadb_config utility.")
    OSError: mariadb_config not found.
    Please make sure, that MariaDB Connector/C is installed on your system, edit the configuration file 'site.cfg' and set the 'mariadb_config'
    option, which should point to the mariadb_config utility.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-2gdw_t_r/mariadb/
```

I do have `/etc/mysql/my.cnf` file.


----------
        
## GPT3.5 Attempt \#0

It seems like the `mariadb_config` utility is missing on your system. You can try installing the `mariadb-connector-c` package which provides this utility. 

You can install it using the following command:

```
sudo apt-get install libmariadb-dev
```

After installing the package, try running the `pip3 install mariadb` command again. If you still face the same issue, you can try setting the `mariadb_config` option in the `site.cfg` file as suggested in the error message.

To do this, create a file named `site.cfg` in the same directory where you are running the `pip3 install mariadb` command and add the following lines to it:

```
[mariadb_config]
mariadb_config = /usr/bin/mariadb_config
```

Make sure to replace `/usr/bin/mariadb_config` with the correct path to the `mariadb_config` utility on your system. 

After adding these lines to the `site.cfg` file, try running the `pip3 install mariadb` command again. This should resolve the issue.

--------

## GPT3.5 Attempt \#1

It seems like the `mariadb_config` utility is not installed on your system. You can try installing it using the following command:

```
sudo apt-get install libmariadb-dev
```

After installing `libmariadb-dev`, try running `pip3 install mariadb` again. If it still doesn't work, you can try setting the `mariadb_config` option in the `site.cfg` file as suggested in the error message. Here's how you can do it:

1. Create a `site.cfg` file in the same directory where you are running the `pip3 install mariadb` command.
2. Add the following lines to the `site.cfg` file:

```
[mariadb_config]
mariadb_config = /usr/bin/mariadb_config
```

3. Save the `site.cfg` file and try running `pip3 install mariadb` again.

This should hopefully resolve the issue.

--------

## GPT3.5 Attempt \#2

It seems like the `mariadb_config` utility is not installed on your system. You can try installing it using the following command:

```
sudo apt-get install libmariadb-dev
```

After installing the `libmariadb-dev` package, try running the `pip3 install mariadb` command again. If it still doesn't work, you can try setting the `mariadb_config` option in the `site.cfg` file manually. Here's how:

1. Create a file named `site.cfg` in the same directory where you are running the `pip3 install mariadb` command.
2. Add the following lines to the `site.cfg` file:

```
[mariadb_config]
mariadb_config = /usr/bin/mariadb_config
```

3. Save the file and try running the `pip3 install mariadb` command again.

This should hopefully resolve the issue.

--------
